version: '3.2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRESQL_LOG_DIR=/var/lib/postgresql/logs
      - POSTGRESQL_LOG_DESTINATION=stderr
      - POSTGRESQL_LOGGING_COLLECTOR=on
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
