version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MOD: Debug
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - 8000:8000
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRESQL_LOG_DIR=/var/lib/postgresql/logs
      - POSTGRESQL_LOG_DESTINATION=stderr
      - POSTGRESQL_LOGGING_COLLECTOR=on
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
